app/models/bill.rb
app/models/payment.rb
app/models/user.rb
db/migrate/20200915111028_create_payments.rb
db/schema.rb
test/models/payment_test.rb

Added the model and dependency for payments

Added the model payment

---

app/controllers/bills_controller.rb
app/models/bill.rb
app/models/payment.rb

changes in mdoels

---

app/controllers/bills_controller.rb
config/routes.rb

added show method

---

db/migrate/20200915132828_add_status_column_to_payment.rb
db/schema.rb

Added status column in payments

---

db/migrate/20200915143516_flat_and_bill_changes.rb
db/schema.rb

Added column

---

app/controllers/bills_controller.rb
app/models/bill.rb
app/views/bills/_form_update_payment.html.erb
app/views/bills/show.html.erb
config/routes.rb
db/schema.rb

Need to deal with update method to mark a payment as paid
Done:  
Create method in Bill to create Payment 
Create the show page for bills

Create method to create payment and show

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/components/index.html.erb
app/views/layouts/application.html.erb

Stil there are cards pending and forms

First version responsive

---

app/assets/stylesheets/application.scss
app/controllers/bills_controller.rb
app/models/bill.rb
app/models/payment.rb
app/views/bills/new.html.erb
app/views/bills/show.html.erb

- Change the view 
- Create method in the bill controller 
- Put methods in BIll Model to make controller smaller

View for Bill Show

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_fonts.scss
app/controllers/components_controller.rb
app/views/components/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar-smartphone.html.erb

Still we have to make the desktop navbar and the forms

Responsive navbar added

---

app/models/bill.rb
app/views/bills/index.html.erb
db/schema.rb

Done with the bill show for division amounts

Added the money rails Gem

---

app/controllers/bills_controller.rb
app/models/bill.rb
app/models/payment.rb
app/views/bills/_form_bill.html.erb
app/views/bills/_form_update_payment.html.erb
app/views/bills/edit.html.erb
app/views/bills/new.html.erb
app/views/bills/show.html.erb

Need to deal with payment_user_id in the edit part

edit bill, update payment , delete bill

---

app/assets/stylesheets/components/_tasks.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/components/index.html.erb

Variables light was added to bootstrap
Variable info was changed to color white
These changes make the hover of all buttons work
The buttons were updated in the components.html

Text white and variables bootstrap changed

---

app/assets/stylesheets/application.scss
app/controllers/flatmembers_controller.rb
app/controllers/flats_controller.rb
app/controllers/pages_controller.rb
app/javascript/controllers/invitations_controller.js
app/models/flat.rb
app/models/user.rb
app/views/flatmembers/invite.html.erb
app/views/flats/_form_flat.html.erb
app/views/flats/index.html.erb
app/views/flats/new.html.erb
app/views/flats/show.html.erb
config/routes.rb
test/controllers/flatmembers_controller_test.rb

Added flatmembers

---

app/controllers/application_controller.rb
app/views/devise/invitations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/users/invitations/edit.html.erb
app/views/users/invitations/new.html.erb
db/schema.rb

Added name and last name fields.

Add fields invitations

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_fonts.scss
app/controllers/application_controller.rb
app/controllers/areas_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar-smartphone.html.erb
app/views/shared/_navbar.html.erb

Added links fior both navbars.

Added links to navbars

---

app/views/flats/_notifications.html.erb

Change the path for area notifications

Fixed the route for area notifications

---

app/views/bills/show.html.erb

If the user has attached a picture = Avatar if not profile logo

Avatar from the user in the show page

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

We need to hide the navbar in desktop only in the homepage

Landing page home

---

app/assets/stylesheets/application.scss
app/views/flats/show.html.erb
app/views/layouts/application.html.erb

Navbar when your are not login is hidden in landing page
Icons for adress in show flat

Hide navbar when landing page, Icons for adress

---

app/views/areas/show.html.erb
app/views/bills/_form_bill_has_paid.html.erb
app/views/bills/_form_bill_hasnt_paid.html.erb
app/views/events/show.html.erb
db/schema.rb

Don't have to refresh when clicking for bills, tasks and events

Simple form errors

---

app/assets/stylesheets/components/_calendar.scss

changed in css classes

---

app/views/bills/show.html.erb

Has paid/ Hasnt paid only for the paying bill user and the payment user 
Request payment only for the paying bill user

Added the logic of seing has paid hasnt paid

---

app/controllers/flatmembers_controller.rb
app/views/flatmembers/invite.html.erb

impossible to succeed coming back to flat after invite 
trick 'mate created!'
button go back added

Added the button to go back

---

app/assets/stylesheets/components/_forms.scss
app/controllers/bills_controller.rb
app/models/bill.rb
app/models/user.rb
app/views/bills/_form_bill.html.erb
app/views/bills/_form_bill_has_paid.html.erb
app/views/bills/_form_bill_hasnt_paid.html.erb
app/views/bills/edit.html.erb
app/views/bills/show.html.erb
config/application.rb
db/migrate/20201020143422_add_member_of_the_bill.rb
db/schema.rb

- Selection of which user is part of the bill
- Changes in the show of a bill for more logic

Adding the member of the bill and changes in the show
